name: Build Job
on: 
  push:
    branches: 
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn install


  Testing:
    runs-on: ubuntu-latest
    needs: Build  # by default the jobs run parallelly, we can set the dependency for a job to run after another
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle